name: Deploy GitHub Pages

on:
  push:
    branches:
      - master
  pull_request:
    branches: [ master ]
jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: All things angular
        uses: AhsanAyaz/angular-deploy-gh-pages-actions
        with:
          github_access_token: ${{ secrets.ACCESS_TOKEN }} # see the Configuration section for how you can create secrets
          build_configuration: staging # The build environment for the app. please look configurations in your angular.json
          base_href: /angular-libraries/   # make sure this corresponds to https://<your_username>.github.io/<base_href>/
          deploy_branch: gh-pages # The branch the action should deploy to.
          build_folder: dist/angular-libraries # The folder where your project is supposed to be after running ng build by the action.
